default:
  territory_count: 6
  territory_positions:
      - [0, 0]
      - [0, 100]
      - [100, 0]
      - [100, 100]
      - [200, 0]
      - [200, 100]
  territory_edges:
      - [0, 1]
      - [0, 2]
      - [1, 2]
      - [2, 4]
      - [2, 3]
      - [4, 5]
      - [3, 5]

botte_neck:
  territory_count: 10
  territory_positions:
      - [0, 0]
      - [0, 400]
      - [100, 150]
      - [100, 300]
      - [200, 0]
      - [200, 400]
      - [300, 150]
      - [300, 300]
      - [400, 0]
      - [400, 400]
  territory_edges:
      - [0, 1]
      - [0, 2]
      - [1, 3]
      - [2, 3]
      - [2, 7]
      - [3, 5]
      - [4, 6]
      - [6, 7]
      - [6, 8]
      - [7, 9]
      - [8, 9]

star:
  territory_count: 19
  territory_positions:
      - [75, 25]
      - [25, 100]
      - [0, 200]
      - [25, 300]
      - [75, 375]
      - [100, 200]
      - [160, 100]
      - [160, 300]
      - [200, 0]
      - [200, 200]
      - [200, 400]
      - [240, 100]
      - [240, 300]
      - [300, 200]
      - [325, 25]
      - [375, 100]
      - [400, 200]
      - [375, 300]
      - [325, 375]
  territory_edges:
      - [0, 6]
      - [1, 6]
      - [1, 5]
      - [2, 5]
      - [3, 5]
      - [3, 7]
      - [4, 7]
      - [5, 9]
      - [6, 8]
      - [6, 9]
      - [7, 9]
      - [7, 10]
      - [8, 11]
      - [9, 11]
      - [9, 12]
      - [9, 13]
      - [10, 12]
      - [11, 14]
      - [11, 15]
      - [12, 17]
      - [12, 18]
      - [13, 15]
      - [13, 16]
      - [13, 17]
ring:
  territory_count: 12
  territory_positions:
      - [0, 200]
      - [75, 75]
      - [75, 325]
      - [150, 200]
      - [200, 0]
      - [200, 150]
      - [200, 250]
      - [200, 400]
      - [250, 200]
      - [325, 75]
      - [325, 325]
      - [400, 200]
  territory_edges:
      - [0, 1]
      - [0, 2]
      - [0, 3]
      - [1, 4]
      - [2, 7]
      - [3, 5]
      - [3, 6]
      - [4, 5]
      - [4, 9]
      - [5, 8]
      - [6, 7]
      - [6, 8]
      - [7, 10]
      - [8, 11]
      - [9, 11]
      - [10, 11]

MOBA:
  territory_count: 17
  territory_positions:
      - [0, 0]
      - [0, 133]
      - [0, 266]
      - [0, 400]
      - [75, 325]
      - [133, 0]
      - [133, 400]
      - [150, 255]
      - [200, 200]
      - [266, 0]
      - [250, 145]
      - [266, 400]
      - [325, 75]
      - [400, 0]
      - [400, 133]
      - [400, 266]
      - [400, 400]
  territory_edges:
      - [0, 1]
      - [0, 5]
      - [0, 8]
      - [1, 2]
      - [1, 7]
      - [1, 8]
      - [2, 3]
      - [2, 4]
      - [3, 4]
      - [3, 6]
      - [4, 6]
      - [4, 7]
      - [5, 8]
      - [5, 9]
      - [5, 10]
      - [6, 11]
      - [7, 8]
      - [7, 11]
      - [8, 10]
      - [8, 11]
      - [8, 15]
      - [8, 16]
      - [9, 12]
      - [9, 13]
      - [10, 12]
      - [10, 15]
      - [11, 16]
      - [12, 13]
      - [12, 14]
      - [13, 14]
      - [14, 15]
      - [15, 16]

